-- buckpal の口座 / 取引テーブル (書籍準拠)。
-- Flyway が起動時にこのマイグレーションを適用する。
-- 以降のスキーマ変更は V2__*.sql, V3__*.sql ... と番号を増やして追加する。

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE activity (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    timestamp         TIMESTAMP    NOT NULL,
    owner_account_id  BIGINT       NOT NULL,
    source_account_id BIGINT       NOT NULL,
    target_account_id BIGINT       NOT NULL,
    amount            BIGINT       NOT NULL,
    PRIMARY KEY (id)
);
